apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    cluster: spin-clouddriver
  name: spin-clouddriver
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 7002
    protocol: TCP
    targetPort: 7002
  selector:
    app: spin
    cluster: spin-clouddriver
  sessionAffinity: None
  type: ClusterIP
